# yaml-language-server: $schema=../../../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Kanti\ServerTiming\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/{Dto,SqlLogging}/*'
      - '../Classes/*/WrapMiddleware.php'
      - '../Classes/*/XClassMiddlewareDispatcher.php'

  Kanti\ServerTiming\Service\RegisterShutdownFunction\RegisterShutdownFunctionInterface:
    class: Kanti\ServerTiming\Service\RegisterShutdownFunction\RegisterShutdownFunction

  Kanti\ServerTiming\Service\SentryServiceInterface:
    class: Kanti\ServerTiming\Service\SentryService

  TYPO3\CMS\Extbase\Mvc\Dispatcher:
    class: Kanti\ServerTiming\Extbase\XClassExtbaseDispatcher

  # this only works in >=v14
  TYPO3\CMS\Core\Http\Application:
    arguments:
      $requestHandler: '@xclass-core-middleware-dispatcher'
  'xclass-core-middleware-dispatcher':
    class: Kanti\ServerTiming\Middleware\XClassMiddlewareDispatcher
    arguments:
      $kernel: '@TYPO3\CMS\Core\Http\RequestHandler'
      $middlewares: '@core.middlewares'

  # this only works in >=v14
  TYPO3\CMS\Backend\Http\Application:
    arguments:
      $requestHandler: '@xclass-backend-middleware-dispatcher'
  'xclass-backend-middleware-dispatcher':
    class: Kanti\ServerTiming\Middleware\XClassMiddlewareDispatcher
    arguments:
      $kernel: '@TYPO3\CMS\Backend\Http\RequestHandler'
      $middlewares: '@backend.middlewares'

  # this only works in >=v14
  TYPO3\CMS\Frontend\Http\Application:
    arguments:
      $requestHandler: '@xclass-frontend-middleware-dispatcher'
  'xclass-frontend-middleware-dispatcher':
    class: Kanti\ServerTiming\Middleware\XClassMiddlewareDispatcher
    arguments:
      $kernel: '@TYPO3\CMS\Frontend\Http\RequestHandler'
      $middlewares: '@frontend.middlewares'
