services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Kanti\ServerTiming\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/{Dto,SqlLogging}/*'
      - '../Classes/*/WrapMiddleware.php'
      - '../Classes/*/XClassMiddlewareDispatcher.php'

  Kanti\ServerTiming\Service\RegisterShutdownFunction\RegisterShutdownFunctionInterface:
    class: Kanti\ServerTiming\Service\RegisterShutdownFunction\RegisterShutdownFunction

  Kanti\ServerTiming\EventListener\ConsoleCommandEventListener:
    tags:
      -
        name: event.listener
        identifier: kanti/server-timing/console-command-event-listener
        event: Symfony\Component\Console\Event\ConsoleCommandEvent
        method: start
      -
        name: event.listener
        identifier: kanti/server-timing/console-terminate-event-listener
        event: Symfony\Component\Console\Event\ConsoleTerminateEvent
        method: stop

  Kanti\ServerTiming\EventListener\MailEventListener:
    tags:
      -
        name: event.listener
        identifier: kanti/server-timing/mail-event-listener
        event: TYPO3\CMS\Core\Mail\Event\BeforeMailerSentMessageEvent
        method: start
      -
        name: event.listener
        identifier: kanti/server-timing/mail-event-listener
        event: TYPO3\CMS\Core\Mail\Event\AfterMailerSentMessageEvent
        method: stop
  Kanti\ServerTiming\EventListener\BootCompletedEventListener:
    tags:
      -
        name: event.listener
        identifier: kanti/server-timing/boot-completed-event-listener
        event: TYPO3\CMS\Core\Core\Event\BootCompletedEvent

  Kanti\ServerTiming\EventListener\FileProcessingEventListener:
    tags:
      -
        name: event.listener
        identifier: kanti/server-timing/file-processing
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent
        method: before

      -
        name: event.listener
        identifier: kanti/server-timing/file-processing
        event: TYPO3\CMS\Core\Resource\Event\AfterFileProcessingEvent
        method: after
